server:
  port: 8888
# our own configuration for the file storage
file:
  storage-dir: "filestorage/images/"
  client-dir: "/images/**"
spring:
  servlet: # this is for file upload
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB


  datasource:
    username: istadlms
    password: ISTAD@LMS
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://152.42.220.220:5433/istad_lms_db
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update # or update
    generate-ddl: true
springdoc:
  swagger-ui:
    path: /


